_wandb:
    value:
        cli_version: 0.21.3
        e:
            qvt4lvibz858vnypow57bsv0pn8w3292:
                codePath: src\rl\train\ppo_test.py
                codePathLocal: src\rl\train\ppo_test.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "509845245952"
                        used: "434820792320"
                email: 310274movie@gmail.com
                executable: C:\Users\user\Desktop\李哲熙\02_財金\RL_Trading\.venv\scripts\python.exe
                git:
                    commit: 2fbc5fbd05b1117adf602ac128f1e7173bb59727
                    remote: https://github.com/JoshuaLee0816/rl-trading.git
                host: LAPTOP-N1U6QE0M
                memory:
                    total: "16856166400"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\user\Desktop\李哲熙\02_財金\RL_Trading\src\rl\train\ppo_test.py
                python: CPython 3.12.10
                root: C:\Users\user\Desktop\李哲熙\02_財金\RL_Trading
                startedAt: "2025-09-11T01:14:24.213209Z"
                writerId: qvt4lvibz858vnypow57bsv0pn8w3292
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.10
            "5": 0.21.3
            "8":
                - 3
            "12": 0.21.3
            "13": windows-amd64
data:
    value:
        file: stocks_20_with_market_index_2015-2020_long.parquet
dqn:
    value:
        batch_size: 64
        buffer_size: 10000
        device: auto
        epsilon_decay: 0.9995
        epsilon_min: 0.05
        epsilon_schedule: per_episode
        epsilon_start: 1
        gamma: 0.99
        lr: 0.0005
        target_update_freq: 100
environment:
    value:
        action_mode: discrete
        initial_cash: 100000
        lookback: 20
        max_holdings: 5
        qmax_per_trade: 10
        reward_mode: daily_return
logging:
    value:
        outdir: logs/runs
        save_summary: false
        save_trades: false
        trade_sample_freq: 1
ppo:
    value:
        actor_hidden: 64
        actor_lr: 0.0003
        batch_size: 64
        clip_epsilon: 0.2
        critic_hidden: 32
        critic_lr: 0.001
        device: cpu
        entropy_coef: 0.05
        epochs: 3
        gae_lambda: 0.95
        gamma: 0.99
        n_steps: 512
        num_envs: 2
        use_subproc: true
        value_coef: 0.5
safety:
    value:
        cool_down_every: 500
        sleep_seconds: 120
training:
    value:
        grad_steps: 1
        model: ppo
        n_episodes: 2000
        save_freq: 5
        seed: 42
        update_every: 512
        warmup_steps: 10000
