training:
  model: "ppo"              # 控制哪個 model 執行
  n_episodes: 5000          # 總訓練集數
  seed: 42                  # 隨機種子
  upload_wandb: true        # 要不要上傳到 W&B
  ckpt_freq: 20            # 每多少 episodes 存一次 checkpoint
  max_ckpts: 10              # 最多保留的 checkpoint 數
  load_checkpoint: false     # 是否從檢查點載入（未用）

  # 以下目前未在 src/rl/train/ppo_train.py 使用（保留以後擴充）
  save_freq: 5              # 每幾集更新一次圖（目前未用）
  update_every: 256         # 每幾步更新一次（未用）
  warmup_steps: 10000       # 開始更新前先收集步數（未用）
  grad_steps: 1             # 每次觸發連續更新幾次（未用）

model:
  encoder:
    type: "temporal_transformer"   # "identity" | "temporal_transformer"
    params:
      d_model: 16
      n_heads: 2
      n_layers: 2
      dropout: 0.1
      k_window: 20
  n_anchor: 0

data:
  file: "full_300/walk_forward/WF_train_2015_2019_full_300.parquet"
  # 單一測試檔仍可用（部分工具會讀這個）
  test_file: "full_300/walk_forward/WF_test_2020_full_300.parquet"
  # 新增：多年份測試檔（ppo_test 會優先找這個）
  test_files:
    "2020": "full_300/walk_forward/WF_test_2020_full_300.parquet"
    "2021": "full_300/walk_forward/WF_test_2021_full_300.parquet"
    "2022": "full_300/walk_forward/WF_test_2022_full_300.parquet"
    "2023": "full_300/walk_forward/WF_test_2023_full_300.parquet"
    "2024": "full_300/walk_forward/WF_test_2024_full_300.parquet"
  features: ["open", "high", "low", "close", "volume", "MA5", "MA34", "MA60", "VMA20", "VMA60", "rsi14"]
  # features: ['open','high','low','close','volume','cash_dividend','stock_dividend','MA5','MA20','MA34','MA60','MA120','VMA20','VMA60','rsi14','macd','macd_signal','macd_hist']

safety:
  cool_down_every: 500
  sleep_seconds: 120

environment:
  initial_cash: 100000
  lookback: 20
  reward_mode: "daily_return"   # "daily_return" | "total_profit"
  action_mode: "discrete"
  max_holdings: 3
  qmax_per_trade: 10

logging:
  outdir: "logs/runs"
  save_summary: false
  save_trades: false
  trade_sample_freq: 1
  wandb_every: 1
  test_every: 1                # 每N個 outer-episode 跑一次 2020–2024 測試

ppo:
  # 執行設備與並行
  device: "mps"                  # mac 上會用 MPS；Windows/無 MPS 會自動 fallback 到 CPU
  num_envs: 2
  use_subproc: false

  # 演算法超參數
  gamma: 0.99
  gae_lambda: 0.95
  clip_epsilon: 0.2
  entropy_coef: 0.05
  value_coef: 0.5

  # 最佳化與批次
  actor_lr: 0.0001
  critic_lr: 0.00003
  batch_size: 256
  n_steps: 512
  epochs: 3

  # 網路結構 two hidden layers in current
  actor_hidden: 128
  critic_hidden: 64
