training:
  model: "ppo"              # 控制哪個 model 執行
  n_episodes: 10000         # 總訓練集數
  seed: 42                  # 隨機種子
  upload_wandb: False        # 要不要上傳到 W&B
  ckpt_freq: 50             # 每多少 episodes 存一次 checkpoint
  max_ckpts: 5              # 最多保留的 checkpoint 數

  # 以下目前未在 src/rl/train/ppo_train.py 使用（保留以後擴充）
  save_freq: 5              # 每幾集更新一次圖（目前未用）
  update_every: 256         # 每幾步更新一次（未用）
  warmup_steps: 10000       # 開始更新前先收集步數（未用）
  grad_steps: 1             # 每次觸發連續更新幾次（未用）
  load_checkpoint: false    # 是否從檢查點載入（未用）

model:
  encoder:
    type: "temporal_transformer"        # "identity"(不做變化) | "temporal_transformer"(啟用transformer self-attention) Actor /Critic 前state要不要經過一個encoder
    params:
      d_model: 2           # Transformer 隱藏維度(每檔最後輸出的向量長度)
      n_heads: 2            # 分成幾個head關注
      n_layers: 1           # Transformer Encoder 疊幾層 => 每層 = self-attention + FFN + 殘差
      dropout: 0.1          # 每層的dropout rate
      k_window: 15          # 要和Training pipeline對齊?
  n_anchor: 0               # 直通特徵的維度數，不經過transformer的部分

data:
  # file: "stocks_20_with_market_index_2015-2020_long.parquet"
  file: "full_300/walk_forward/WF_train_2015_2019_full_300.parquet"  # 資料檔路徑
  features: ["open", "high", "low", "close", "volume", "MA5", "MA34", "MA60", "VMA20", "VMA60", "rsi14"]
  #features: ['open', 'high', 'low', 'close', 'volume', 'cash_dividend', 'stock_dividend', 'MA5', 'MA20', 'MA34', 'MA60', 'MA120', 'VMA20', 'VMA60', 'rsi14', 'macd', 'macd_signal', 'macd_hist']  # 要保留的特徵

safety:
  cool_down_every: 500      # 每多少 episodes 強制休息（目前未用）
  sleep_seconds: 120        # 休息秒數（目前未用）

environment:
  initial_cash: 100000      # 初始資金
  lookback: 15              # 向前看的天數
  reward_mode: "daily_return"   # "daily_return" | "total_profit"
  action_mode: "discrete"   # 動作模式
  max_holdings: 3           # 最多同時持有幾檔
  qmax_per_trade: 10        # 單檔單次最大交易張數

logging:
  outdir: "logs/runs"       # 輸出目錄
  save_summary: false       # 是否存 summary.csv
  save_trades: false        # 是否存 trades_all.csv（目前未用）
  trade_sample_freq: 1      # 每幾筆交易存一次（寫入 RunLogger）
  wandb_every: 1            # 每幾個 episode 紀錄一次到 W&B

ppo:
  # 執行設備與並行
  device: "cpu"
  num_envs: 1
  use_subproc: false

  # 演算法超參數
  gamma: 0.998
  gae_lambda: 0.95
  clip_epsilon: 0.2
  entropy_coef: 0.1
  value_coef: 0.5

  # 最佳化與批次
  actor_lr: 0.00001
  critic_lr: 0.00003
  batch_size: 64
  n_steps: 512
  epochs: 1                 # 每次 update 的 epoch 數

  # 網路結構
  actor_hidden: 8
  critic_hidden: 8

dqn:                         # 目前未用（model=ppo 時忽略）
  gamma: 0.99
  epsilon_schedule: "per_episode"   # "per_episode" | "per_step"
  epsilon_start: 1.0
  epsilon_min: 0.05
  epsilon_decay: 0.9995
  lr: 0.0005
  batch_size: 64
  buffer_size: 10000
  target_update_freq: 100
  device: "auto"            # "cpu" | "mps" | "cuda" | "auto"
